### ISSUE TITLE
"Site.com"/upload didn't work and demo don't recording

### ISSUE THREAD

**Issue by JoJaCode** [sapsanDev/CS2--DemoRecoder#3]
Site said, that there is no get any response when try to go http://examle.com/upload and demos don't recording.
Maybe need set anything else?

**Comment by sapsanDev** [comment]
Did you forward port to port 80 from 5053?

**Comment by JoJaCode** [comment]
Yeah. I'm using Google Cloud and open port 80 and 2053 (in my case) to instance. But 2053 port is work fine, but port 80 - isn't. 
And I have one problem too:
```PM2      | App [demos:0] starting in -fork mode-
PM2      | App [demos:0] online
0|demos  | Error: Cannot find module 'node:path'
0|demos  | Require stack:
0|demos  | - /home/hackon189/node_modules/express-handlebars/dist/express-handlebars.js
0|demos  | - /home/hackon189/node_modules/express-handlebars/dist/index.js
0|demos  | - /home/hackon189/demos.js
0|demos  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
0|demos  |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:81:25)
0|demos  |     at require (internal/modules/cjs/helpers.js:74:18)
0|demos  |     at Object.<anonymous> (/home/hackon189/node_modules/express-handlebars/dist/express-handlebars.js:19:14)
0|demos  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
0|demos  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
0|demos  |     at Module.load (internal/modules/cjs/loader.js:863:32)
0|demos  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
0|demos  |     at Module.require (internal/modules/cjs/loader.js:887:19)
0|demos  |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39) {
0|demos  |   code: 'MODULE_NOT_FOUND',
0|demos  |   requireStack: [
0|demos  |     '/home/hackon189/node_modules/express-handlebars/dist/express-handlebars.js',
0|demos  |     '/home/hackon189/node_modules/express-handlebars/dist/index.js',
0|demos  |     '/home/hackon189/demos.js'
0|demos  |   ]
0|demos  | }
PM2      | App [demos:0] exited with code [1] via signal [SIGINT]
PM2      | Script /home/hackon189/demos.js had too many unstable restarts (16). Stopped. "errored"
```

Here is Chat GPT history how I'm trying to solve this problem: https://chat.openai.com/share/58621cf9-1c02-4e0f-bdcf-9dc1f5c6f197

**Comment by JoJaCode** [comment]
As I see, it Google Cloud problem to open port 80. I'm trying to solve it. It's not code problem or anything else...
P.s. About module - it solved

**Comment by JoJaCode** [comment]
Okay, port 80 works but "site.com"/upload didn't work
P.s. How can I contact with you to show it?
